# Generated by Django 4.2.7 on 2023-11-25 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=93, verbose_name="ФИО")),
                ("phone", models.CharField(max_length=15, verbose_name="Телефон")),
            ],
            options={
                "verbose_name": "контакт",
                "verbose_name_plural": "контакты",
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_audio", models.FileField(upload_to="conversation_audio/")),
            ],
            options={
                "verbose_name": "разговор",
                "verbose_name_plural": "разговоры",
            },
        ),
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=93, verbose_name="ФИО")),
            ],
            options={
                "verbose_name": "оператор",
                "verbose_name_plural": "операторы",
            },
        ),
        migrations.CreateModel(
            name="Transcription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operator_transcription", models.TextField()),
                ("contact_transcription", models.TextField()),
            ],
            options={
                "verbose_name": "транскрипция",
                "verbose_name_plural": "транскрипции",
            },
        ),
        migrations.CreateModel(
            name="DialogCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("call_date", models.DateTimeField(verbose_name="Дата и время звонка")),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dialogs.contact",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dialogs.conversation",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dialogs.operator",
                    ),
                ),
            ],
            options={
                "verbose_name": "карточка контакта",
                "verbose_name_plural": "карточки контакта",
            },
        ),
        migrations.AddField(
            model_name="conversation",
            name="transcription",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation",
                to="dialogs.transcription",
            ),
        ),
    ]
