# Generated by Django 4.2.7 on 2023-11-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dialogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dialogcard",
            options={
                "verbose_name": "карточка контакта",
                "verbose_name_plural": "карточки контактов",
            },
        ),
        migrations.AlterField(
            model_name="conversation",
            name="contact_audio",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="transcription",
            name="contact_transcription",
            field=models.JSONField(
                blank=True, null=True, verbose_name="транскрипция клиента"
            ),
        ),
        migrations.AlterField(
            model_name="transcription",
            name="operator_transcription",
            field=models.JSONField(
                blank=True, null=True, verbose_name="транскрипция оператора"
            ),
        ),
    ]
