# Generated by Django 4.2.7 on 2023-11-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dialogs", "0002_alter_dialogcard_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dialogcard",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "Новое"),
                    ("Work", "В работе"),
                    ("Done", "Обработано"),
                ],
                default="Новое",
                max_length=512,
            ),
        ),
    ]
